[package]
name = "blarf"
version = "1.0.0"
authors = ["Tom Ragle <tragle@gmail.com>"]
edition = "2018"

[dependencies]
pulldown-cmark = { version = "0.2.0", default-features = false }
clap = "2.32.0"
